---

- command: openssl dhparam -out /etc/ssl/certs/dhparams-16073.pem 2048 creates=/etc/ssl/certs/dhparams-16073.pem

- name: Get nginx version
  shell: /usr/sbin/nginx -v 2>&1 | cut -d/ -f2
  register: nginx_version
  changed_when: no
  
- copy: src=mit-default-https.conf-{{ nginx_version.stdout }} dest=/etc/nginx/conf.d/mit-default-https.conf
  notify: Restart nginx  

