---
# Even on FreeBSD we use /etc/ssl/certs
- name: Generate dhparams-16073.pem
  ansible.builtin.command: openssl dhparam -out /etc/ssl/certs/dhparams-16073.pem 2048
  args:
    creates: /etc/ssl/certs/dhparams-16073.pem

- name: Get nginx version
  ansible.builtin.shell: nginx -v 2>&1 | cut -d/ -f2
  register: nginx_version
  changed_when: false

- name: Copy local-mit-default-https.conf
  ansible.builtin.template:
    src: local-mit-default-https.conf-{{ nginx_version.stdout }}
    dest: "{{ etc_prefix }}/etc/nginx/conf.d/local-mit-default-https.conf"
  notify: Reload nginx

- name: Remove deprecated mit-default-https.conf
  ansible.builtin.file:
    path: "{{ etc_prefix }}/etc/nginx/conf.d/mit-default-https.conf"
    state: absent
  notify: Reload nginx

# - debug: msg="{{ nginx_version }}"
#20250: ssl_protocols < TLSv1.2 sollten ab 2020-01 nicht mehr unterstuetzt werden
# Debian 9 / nginx 1.10 doesn't support TLSv1.3
- name: Disable ssl_protocols < TLSv1.2 (nginx < 1.14)
  ansible.builtin.lineinfile:
    dest: "{{ etc_prefix }}/etc/nginx/nginx.conf"
    regexp: "^\tssl_protocols "
    line: "\tssl_protocols TLSv1.2; #20250: Dropping protocols < TLSv1.2"
  notify: Reload nginx
  when: nginx_version.stdout is version_compare('1.14', operator='<')

# The options below are included in local-mit-default-https.conf-VERSION
# and need to be removed from nginx.conf to avoid collisions.
- name: Remove colliding global options
  ansible.builtin.lineinfile:
    dest: "{{ etc_prefix }}/etc/nginx/nginx.conf"
    regexp: ^\s*(gzip|ssl_prefer_server_ciphers|ssl_protocols)\s
    state: absent
    mode: "0644"
  notify: Reload nginx
  when: nginx_version.stdout is version_compare('1.14', operator='>=')
